# Generated by Django 2.0.7 on 2018-07-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180720_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='listing_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
