# Generated by Django 2.0.7 on 2018-07-20 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180720_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cell',
            field=models.CharField(default='03214567890', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.images'),
        ),
    ]
